name: redisx package
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - master
    paths:
      - 'redisx.rb'
      - '.github/workflows/redisx.yml'

  pull_request:
    paths:
      - 'redisx.rb'
      - '.github/workflows/redisx.yml'

jobs:           
  check:
    name: Check redisx
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - option:
          - option: --without-libomp
          - option: --without-openssl
          - option: --with-doxygen

    steps:
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Build and install
        run: |
           brew tap attipaci/pub
           brew install redisx ${{matrix.option}}

  pkginfo:
    name: Update package info
    needs: check
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main
    
      - name: Checkout pkginfo branch
        uses: actions/checkout@v7
        with:
          ref: 'pkginfo'
          path: 'pkginfo'
    
      - name: Generate package info
        run: |
          brew tap attipaci/pub
          brew info --json redisx | jq '.[0]? // .' > pkginfo/redisx.json

      - name: Commit and Push package info
        run: |
          cd pkginfo
          git config --global user.email "$GITHUB_JOB+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add -A
          git commit -m "automated package info update" && git push || true
