name: xchange package
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - master
    paths:
      - 'xchange.rb'
      - '.github/workflows/xchange.yml'

  pull_request:
    paths:
      - 'xchange.rb'
      - '.github/workflows/xchange.yml'

jobs:           
  check:
    name: Check xchange
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - description: default configuration
            option:
          - description: with documentation
            option: --with-doxygen

    env:
      HOMEBREW_NO_SANDBOX_LINUX: 1
    steps:
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        
      - name: Build and install
        run: |
           brew tap attipaci/pub
           brew install xchange ${{matrix.option}}

  pkginfo:
    name: Update package info
    needs: check
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main
    
      - name: Checkout pkginfo branch
        uses: actions/checkout@v7
        with:
          ref: 'pkginfo'
          path: 'pkginfo'
    
      - name: Generate package info
        run: |
          brew tap attipaci/pub
          brew info --json xchange | jq '.[0]? // .' > pkginfo/xchange.json

      - name: Commit and Push package info
        run: |
          cd pkginfo
          git config --global user.email "$GITHUB_JOB+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add -A
          git commit -m "automated package info update" && git push || true
